image: Visual Studio 2019

environment:
  NODE_CONFIG: '{"db": {"host": "localhost"}}'
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\13
  matrix:
    - nodejs_version: "16"

services:
  - postgresql13

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install pnpm -g
  - pnpm install

before_test:
  - set path=%postgres_path%\\bin;%path%
  - "psql -c \"create database \\\"atributo\\\";\""

test_script:
  - npx node-pg-migrate up
  - .\node_modules\.bin\grunt lint test-all-db

build: off
