environment:
  NODE_CONFIG: '{"db": {"host": "localhost"}}'
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\10
  matrix:
    - nodejs_version: "12"

services:
  - postgresql101

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

before_test:
  - set path=%postgres_path%\\bin;%path%
  - "psql -c \"create database \\\"atributo\\\";\""

test_script:
  - npm run migrate up
  - .\node_modules\.bin\grunt lint test-all-db

build: off
