environment:
  matrix:
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - .\node_modules\.bin\grunt lint test-all-db

build: off
