version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
        environment:
          CXX: g++-6
          NODE_CONFIG: '{"db":{"host":"localhost","database":"atributo","migrations-dir":"pg-migrations","user":"postgres"}}'
      - image: circleci/postgres:11.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: atributo
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo bash -c 'echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
            sudo apt-get -y update
            sudo apt-get -y install -t unstable g++-6 lcov
            npm install
      - run:
          name: test
          command: |
            npm run pg-migrate up
            ./node_modules/.bin/grunt lint coverage coveralls
