version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.7.0-buster
        environment:
          NODE_CONFIG: '{"db":{"host":"localhost","database":"atributo","migrations-dir":"pg-migrations","user":"postgres"}}'
          PGHOST: localhost
          PGDATABASE: atributo
          PGUSER: postgres
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: atributo
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt -y update
            sudo apt -y install lcov postgresql-client libsqlite3-dev
            npm install
      - run:
          name: test
          command: |
            npm run pg-migrate up
            ./node_modules/.bin/grunt lint coverage coveralls
