name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      NODE_CONFIG: '{"db": {"host": "localhost"}}'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Lint
        run: npx grunt lint

      - name: Create database
        run: "psql -c \"create database \\\"atributo\\\";\""

      - name: Apply migrations
        run: npx node-pg-migrate up

      - name: Test
        run: npx grunt tets-all-db
